### ISSUE TITLE
search for string with multiple words separated by space not providing "OR" results.

### ISSUE THREAD

**Issue by jeffreycwitt** [scta/scta-app#5]
After update to existdb 5.3 search results when using simpleXmlCoordinates search don't seem to be giving "or" results when two words separated by space are sent as the search query. 

So if you send `omnis omnipotens` only lines that contain "omnis" and "omnipotens" in the same line are returned. But they don't have to be consecutive. 

In other words, the search is returning something like: "all lines that contain the words 'omnis' and 'omnipotens' anywhere in the line. They don't have to be consecutive, but they both have to be there. 

Previously, it would just be a simple "or": all lines that container either "omnis" OR "omnipotens". 

Oddly this is still the behavior when running the main text search.

**Comment by joewiz** [comment]
Assuming that you're using eXist's Lucene-based full text index with `ft:query()` and passing it your query as a string, this function can take an `$options` parameter, as described in https://exist-db.org/exist/apps/doc/lucene#parameters. One of the options is `default-operator`, which sets whether multiple terms are combined with OR or AND by default. Without providing this parameter, the default is OR (I believe), but you might check whether you're overriding this default with this `$options` parameter. 

If you're passing `ft:query()` your query [as XML](https://exist-db.org/exist/apps/doc/lucene#describe), then should check to see if you're using any of the boolean, near, or slop options in that format.

**Comment by jeffreycwitt** [comment]
Wow, I didn't know you followed my issues list!

Explicitly adding add the "OR" parameter through the options seems to have worked!

The only thing that is strange is why it is needed to be explicitly set in this case since OR is the default option.

The default OR was operational when I was using 3.1. 

And my other ft:query call (on a different indexed set of texts) is still respecting the default OR parameter. 

Weird. But I guess that's just a question for speculation. Seems like your suggestion has solved my issue!!! 

(p.s. now that I know you're following this issues list, you'd better be careful. I might start recording lots of issues :)
